@startuml
left to right direction
skinparam packageStyle rectangle

actor "Utilisateur" as User
actor "Professionnel de santé" as Pro
actor "Administrateur" as Admin

User <|-- Pro
User <|-- Admin

rectangle "Système d'information médical" {

  usecase "S'authentifier" as UC_Auth

  usecase "Inscrire patient" as UC_Inscrire
  usecase "Programmer et suivre consultation" as UC_Programmer
  usecase "Consulter et mettre à jour\ndossier médical" as UC_Dossier
  usecase "Vérifier la disponibilité" as UC_Dispo

  usecase "Créer compte utilisateur" as UC_CreerCompte
  usecase "Supprimer compte utilisateur" as UC_SupprimerCompte
  usecase "Gérer les droits d'accès" as UC_Droits
  usecase "Consulter statistiques" as UC_Stats
}

Pro -- UC_Inscrire
Pro -- UC_Programmer
Pro -- UC_Dossier

Admin -- UC_CreerCompte
Admin -- UC_SupprimerCompte
Admin -- UC_Droits
Admin -- UC_Stats

User -- UC_Auth

UC_Inscrire ..> UC_Auth : <<include>>
UC_Programmer ..> UC_Auth : <<include>>
UC_Dossier ..> UC_Auth : <<include>>
UC_CreerCompte ..> UC_Auth : <<include>>
UC_SupprimerCompte ..> UC_Auth : <<include>>
UC_Droits ..> UC_Auth : <<include>>
UC_Stats ..> UC_Auth : <<include>>

UC_Programmer ..> UC_Dispo : <<include>>

@enduml
